apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template: 
    metadata: 
      name: myapp1-prod
      labels: 
        app: myapp1
    spec: 
      containers: 
      
    

